#!/system/bin/sh

#
# SkyLine Kernel Config
# Creater: urK
#

# Export
export INTERNAL_STORGE=/sys/block/mmcblk0
export EXTERNAL_STORGE=/sys/block/mmcblk1

# CPU
# echo 453120 >> /sys/bus/cpu/devices/cpu0/cpufreq/scaling_min_freq
# echo schedalucard >> /sys/bus/cpu/devices/cpu0/cpufreq/scaling_governor

# GPU

# I/O
echo zen >> $INTERNAL_STORGE/queue/scheduler
echo 1000 >> $INTERNAL_STORGE/queue/iosched/async_expire
echo 50 >> $INTERNAL_STORGE/queue/iosched/sync_expire

echo zen >> $EXTERNAL_STORGE/queue/scheduler
echo 1000 >> $EXTERNAL_STORGE/queue/iosched/async_expire
echo 50 >> $EXTERNAL_STORGE/queue/iosched/sync_expire

# Function Enable
echo 1 >> /sys/kernel/fp_boost/enable
# echo 1 >> /sys/kernel/dyn_fsync/Dyn_fsync_active

# Done