language: c
before_install:
 - sudo apt update
 - sudo apt upgrade -y
install: ccache bc bash git-core gnupg build-essential zip curl make automake autogen autoconf autotools-dev libtool shtool python m4 gcc libtool zlib1g-dev
script: build-ci.sh
